# Generated by Django 3.1 on 2020-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_author_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_accessed',
            field=models.DateTimeField(null=True),
        ),
    ]
